#!/bin/bash

options=(
	style=square
	width=8.0
    order=above
	hidpi=on
	active_color=0xfffe8019
	inactive_color=0xff504945
	background_color=0x302c2e34
    # blacklist="firefox"
)

borders "${options[@]}"

