#!/bin/bash

options=(
	style=round
	width=5.0
    order=above
	hidpi=on
	active_color=0xc0e2e2e3
	inactive_color=0xff414550
	background_color=0x302c2e34
    blacklist="zen"
)

borders "${options[@]}"

