# --- Color Scheme (Nord-inspired from your TOML) ---

# Tab Bar
active_tab_foreground   #282c34
active_tab_background   #979eab
inactive_tab_foreground #abb2bf
inactive_tab_background #282c34

foreground #D8DEE9
background #151515
# Cursor colors
cursor            #D8DEE9
cursor_text_color #2E3440

# Normal Colors
color0 #181818
color1 #ac4242
color2 #90a959
color3 #f4bf75
color4 #6a9fb5
color5 #aa759f
color6 #75b5aa
color7 #d8d8d8

# Bright Colors
color8  #6b6b6b
color9  #c55555
color10 #aac474
color11 #feca88
color12 #82b8c8
color13 #c28cb8
color14 #93d3c3
color15 #f8f8f8
