include current-theme.conf

# font_family VictorMono Nerd Font Mono
# bold_font auto
# italic_font auto
# bold_italic_font auto

# font_family        Hasklug Nerd Font Mono
# bold_font          Hasklug Nerd Font Mono Bold
# italic_font        Hasklug Nerd Font Mono Italic
# bold_italic_font   auto

font_family        Fira Mono
bold_font          auto
italic_font        auto
bold_italic_font   auto


# font_family        JetBrainsMono Nerd Font 
# bold_font          auto
# italic_font        auto
# bold_italic_font   auto
#

# Font size (in pts)
# Do not use odd values as these affect how kitty renders margin
font_size         20

mouse_hide_wait -1

window_padding_width 5
background_opacity 1

enable_audio_bell no

map cmd+c        copy_to_clipboard
map kitty_mod+v  paste_from_clipboard
map cmd+v        paste_from_clipboard

# Colors
macos_option_as_alt yes

hide_window_decorations titlebar-only
macos_fullscreen_ignore_safe_area_insets yes
macos_traditional_fullscreen yes
placement_strategy top-left

allow_remote_control yes
listen_on unix:/tmp/mykitty
