#!/usr/bin/env sh
sudo yabai --load-sa 

# Global settings
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config window_gap 0
yabai -m config top_padding 0
yabai -m config window_shadow off
yabai -m config window_border off

yabai -m config external_bar all:0:0


# Mouse settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Ignore standard macOS popups and system apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add title="Settings" manage=off

echo "yabai configuration loaded"
